### ISSUE TITLE
Renew Let's Encrypt certificate (automatically)

### ISSUE THREAD

**Issue by EwoutH** [xiph/awcy#190]
The Let's Encrypt certificate expired:

![Screenshot_492](https://user-images.githubusercontent.com/15776622/72681434-d1233280-3ac3-11ea-8288-a26a0b8eab54.png)

Related to #167.

**Comment by rzumer** [comment]
That would be nice, but that's not an AWCY issue.

**Comment by rzumer** [comment]
This seems to have been solved, regardless of my previous comment, so closing.
