### ISSUE TITLE
Media files not available

### ISSUE THREAD

**Issue by aizvorski** [xiph/awcy#204]
The readme says:

> MEDIAS_SRC_DIR=/data/media: directory containing media files ( get them from https://people.xiph.org/~tdaede/sets/ )

Unfortunately the link is dead.  Is there someplace the media files can be downloaded?  

Perhaps from an S3 bucket? :)

```
$ wget --mirror https://people.xiph.org/~tdaede/sets/
--2020-06-30 03:55:58--  https://people.xiph.org/~tdaede/sets/
Resolving people.xiph.org (people.xiph.org)... 140.211.166.31, 2001:470:eb26:42::1
Connecting to people.xiph.org (people.xiph.org)|140.211.166.31|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-30 03:55:58 ERROR 404: Not Found.
```

**Comment by veikk0** [comment]
Just found out the test sets have moved to https://media.xiph.org/video/derf/. Links to all the sets are on the bottom of that page.

**Comment by rzumer** [comment]
I have updated the link, many sets are now available at https://media.xiph.org/sets/.
Fixed by https://github.com/xiph/awcy/commit/56455d3a1cff264b47f399686cdae26060626f55.
