### ISSUE TITLE
beta.arewecompressedyet.com fails to compile SVT-AV1

### ISSUE THREAD

**Issue by tdaede** [xiph/awcy#311]
It prefers clang, but is finding the emscripten clang. We need to hide this from SVT-AV1 in the build script, or install a system clang for it to find first.

**Comment by 1480c1** [comment]
One possible fix I can see is on 
https://github.com/xiph/awcy/blob/master/build_codec.sh#L128 to add `--cc="gcc"` or `--cc="cc"` to make it use gcc or whatever is the default cc. Preferably the same compiler as aom/avm

**Comment by 1480c1** [comment]
Alternatively, just using cmake directly would also probably be fine as well

**Comment by vibhoothi** [comment]
quick ping to bring this up.
